apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-app
  labels:
    app: java-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-web-app
  template:
    metadata:
      labels:
        app: java-web-app
    spec:
      containers:
      - name: java-app
        image: rajagopal/java-devops-demo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: java-web-app
